# Generated by Django 6.0.6 on 2026-07-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_aischolarshiprecommendation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIScholarshipRecommendation",
        ),
    ]
