# Generated by Django 6.0.6 on 2026-06-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(default="Australia", max_length=100)),
                ("world_ranking", models.PositiveIntegerField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("logo_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField()),
            ],
            options={
                "verbose_name_plural": "universities",
                "ordering": ["world_ranking", "name"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full", "Full Scholarship"),
                            ("partial", "Partial Scholarship"),
                            ("full_ride", "Full Ride"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("eligibility", models.TextField()),
                ("deadline", models.DateField(blank=True, null=True)),
                ("link", models.URLField()),
                ("field", models.CharField(blank=True, max_length=100)),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scholarships",
                        to="catalog.university",
                    ),
                ),
            ],
            options={
                "ordering": ["deadline", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[("masters", "Master's"), ("phd", "PhD")], max_length=10
                    ),
                ),
                ("field", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
                (
                    "tuition_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("requirements", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("application_url", models.URLField()),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="catalog.university",
                    ),
                ),
            ],
            options={
                "ordering": ["university__name", "title"],
            },
        ),
    ]
