# Generated by Django 6.0.6 on 2026-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
